# Generated by Django 4.2.1 on 2023-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredients",
                    models.CharField(max_length=500, verbose_name="Ingredients Names"),
                ),
                ("quantity", models.CharField(max_length=100)),
                ("recipe", models.ManyToManyField(to="dishapp.recipe")),
            ],
        ),
    ]
