# Generated by Django 4.2.1 on 2023-06-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishapp", "0003_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="recipe",
            new_name="recipe_name",
        ),
    ]
