# Generated by Django 4.2.1 on 2023-06-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dishapp", "0004_rename_recipe_ingredient_recipe_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="recipe",
            new_name="recipe_id",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="recipe_name",
            new_name="recipe_id",
        ),
    ]
